### PR TITLE
Improve watchdog behavior re. LTE modem deinit

### PR DESCRIPTION
**Pull request by pinguin999**
The device stopped at `lte.deinit()` so I moved the watchdog up.

### CODE REVIEW

**Comment by amotl** [comment]
Dear @pinguin999,

thanks for getting closer to the source code of this little thing we are conceiving here. We are happy to see you join our collaborative efforts.

We found that the `lte.deinit()` takes about 5 seconds so it is not unreasonable that the watchdog hits the fan when configured to a lower interval. Thanks for actually taking the time to test, observe and report this behavior to us.

As we have been unsure about power-related issues regarding initialization / teardown of the LTE modem, we are thinking about removing the `lte.deinit()` altogether in one of the next iterations, followed up by another round of ampere measurements.

Would that also be a valid option for you?

With kind regards,
Andreas.

**Comment by pinguin999** [comment]
@amotl You can remove the lte.deinit() for testing. But for deep sleep it is needed.

machine.deepsleep([time_ms])
Stops the CPU and all peripherals, including the networking interfaces (except for LTE). Execution is resumed from the main script, just as with a reset. If a value in milliseconds is given then the device will wake up after that period of time, otherwise it will remain in deep sleep until the reset button is pressed.

The products with LTE connectivity (FiPy, GPy, G01), require the LTE radio to be disabled separately via the LTE class before entering deepsleep. This is required due to the LTE radio being powered independently and allowing use cases which require the system to be taken out from deepsleep by an event from the LTE network (data or SMS received for instance).

**Comment by amotl** [comment]
Dear @pinguin999,

thanks for your feedback. We just added an appropriate recap to [1]. While we might revisit it, it's good to keep as a record. Discussions about that topic will be easier in Discourse as more people are involved there.

With kind regards,
Andreas.

[1] https://community.hiveeyes.org/t/deep-sleep-with-fipy-esp32-on-micropython/1792/18

**Comment by amotl** [comment]
Dear @pinguin999,

> The device stopped at lte.deinit() so I moved the watchdog up.

I believe I had the same thing happening to me yesterday, so I also would like to move the watchdog up. We would have to make sure that the timeout will be temporarily increased to ~7-10 seconds when configured to a lower value per configuration settings.

We also might think about limiting the minimum timeout to something like 20-30 seconds or even more to make the watchdog not accidentally pull the trigger when some procedure will take longer than anticipated.

Currently, the WDT is fed from some specific spots throughout the code (it's not running in a corresponding service thread), so the feeding is not done in regular intervals. We will be happy about respective feedback if you have requests for changes to that.

May we humbly ask you to clean the PR from the Touch/Button disablement? We just added eb0e33da where the `ButtonManager` will now be imported lazily - if that might have been some obstacle for you.

Thanks,
Andreas.

**Comment by amotl** [comment]
We just have been able to experience this issue again which looks like that:
```python
>>> from network import LTE
>>> lte = LTE()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OSError: Couldn't connect to Modem!
```

**Comment by amotl** [comment]
Dear @pinguin999,

thank you so much for your contribution. We added some bells and whistles and described the outcome at [Watchdog updates](https://community.hiveeyes.org/t/kontinuierliche-verbesserungen-des-terkin-datenloggers-600er/2121/84).

We will be happy to hear back from you if this solves the occasional hiccups you have been able to observe when running the firmware with shields enabled.

With kind regards,
Andreas.

**Pull request closed without merging**
